sudo: required

language: android

services:
  - docker

notifications:
  email: false

before_install:
- openssl aes-256-cbc -K $encrypted_82aeeacd91a7_key -iv $encrypted_82aeeacd91a7_iv
  -in snowdream.keystore.enc -out snowdream.keystore -d
- docker pull snowdream/docker-android:1.0
- sudo docker run -t -i snowdream/docker-android:1.0 /bin/bash

script:
- gradle clean test --info